### PR TITLE
Fix inconsistencies between conceptual, logical, and physical schemas; introduce RBAC; remove schema qualifications

### LINKED ISSUE #41: ER schema is inconsistent with the relational schema (M)
The ER schema is quite inconsistent with the relational schema. It does not seem to have been updated as the relational schema changed.

### LINKED ISSUE #74: Database object names are schema-qualified
Database objects such as tables, views, and functions are presently schema-qualified specifically with the schema name `Gradebook`, which requires each tenant to unnecessarily use a dedicated database for each tenant.

The better approach is to **not** schema-qualify object names and execute various object-creation and alteration scripts in the context of a tenant-specific schema.

The proposed revision also makes dev and testing easy because database objects can easily be created in temporary schemas.

The required change is rather simple: simply remove schema name from database object names. For example, replace all instances of the names `Gradebook.Instructor` and `Gradebook.getScheduleDates` with just `Instructor` and `getScheduleDates`, respectively.

### PR DESCRIPTION
**Pull request by afig**
This PR addresses inconsistencies that existed between the conceptual/ER relational, and physical schemas in Gradebook. This was addressed by working off the schemas created in the CS305-Alpha fork and making changes (or more specifically, undoing changes) to make it contain only the features that were already implemented in DASSL's Gradebook.

The following changes were made to the conceptual schema to address inconsistencies:

- `Course` entity
    - Change `Description` to `Title`
- `Section` entity
    - Change PK from `CRN` to `ID`
    - Add `CRN` as a non-key attribute
    - Add attributes `Start Date` and `End Date`
- `Term` entity
    - Change PK from `{Year, Season}` to `ID`
    - Add `Year` attribute
- Relationship between `Enrollee`, `Assessment Component`, and `Assessment Item`
    - Give name to unnamed entity
    - Add relationship attributes between `Assessment` and `Assessment Item`
    - Add name to entity formed by tertiary relationship (`Assessment`)
- Entity `Student`
    - Change `Name` to composite attribute that includes full, middle, last name
    - Add `School Issued ID` attribute
    - Add `Email` attribute
- Entity `Enrollee`
    - Add `Enrollment Major` and `Enrollment Year` attributes
    - Add `Midterm Weighted Aggregate` and `Final Weighted Aggregate` attributes
    - Change grades into 2 composite attributes
- Add Entity `Attendance Status`
    - Add PK `Status`
    - Add attribute Description
- Entity `Attendance Record`
    - Remove `Status` attribute (is actually a part of Attendance Status)
- Entity `Grade`
    - Add attribute `GPA`
- Entity `Instructor`
    - Change `Name` to a composite attribute containing full, middle, last name

A copy of the previous conceptual schema is available in `docs/M1ConceptualSchema.png`. This file may be removed before this PR is merged, depending on discussion. (The file will still be available through the repository's history.)

A full Logical schema (`docs/M2LogicalSchema.docx`) was added with descriptions for each table, as opposed to the previous logical schema which only contained a logical schema that was not fully consistent with either the old conceptual or physical schemas.

Finally, the physical schema was updated to be consistent with the conceptual and logical schemas. Since this was based off of the CS305-Alpha fork, many other changes were also introduced, most of which have been undone. However, a few were kept as they align with desired changes to Gradebook in general. The following changes were kept:

- Removing schema qualification from tables and functions. Instead, the `LOCAL search_path` is set at the script-level. Currently, the search path is set to `'gradebook', 'pg_temp'` for backwards compatibility and having a generic schema name to use for development. `SECURITY DEFINER` functions use the `SET search_path FROM CURRENT` clause ensure that the `pg_temp` schema is always checked last.

- Adding role-based access control to tables and some functions. Only users with the `gb_dbadmin` (or `superuser`) role can directly modify tables. Any modifications must be made through appropriate functions. Many essential functions do not currently exist in Gradebook, but will likely be added in future milestones.

- Addition of a `dropFunctions.sql` script that drops all functions defined by Gradebook.

@jrm86 and I would appreciate an outside review or two. In addition, we have a question about copyright/author names. Since some of these additions were directly copied over from work done by Team Alpha in CS305, how should credit be given? Since @jrm86 and I are DASSL members, we simply added our name to the list. However, the remaining member of Team Alpha is not a DASSL member.

Also, apologies in advance for the huge PR that is essentially implementing three distinct changes (see title). Ideally this would have been split into ~3 different PRs, but doing so would require extensive, error-prone work that may not have a huge net-benefit.

Closes #41, Closes #74

### CODE REVIEW

**Comment by smurthys** [comment]
Thanks @afig and @jrm86 for the contribution. I will review the changes during the day between other work. I hope other reviewers will share their thoughts in the meanwhile.

**Comment by smurthys** [comment]
Please add the names of anyone who made meaningful contribution toward the changes included in the PR. Use the guidelines we have generally used in the past to determine if a name should be included. It is OK for non-members of DASSL to contribute.

**Comment by afig** [comment]
Upon review of the PR, @jrm86 and I have determined that this PR implements several changes that are outside of the scope of M2. Although these changes are generally useful, they unnecessarily add to the effort needed to review this PR and ensure high-quality work.

@jrm86 and I propose that this PR be closed and a new one opened. The new PR would only implement the updates to the conceptual and logical schemas. If the team agrees that this is a better approach, then @jrm86 or I would close this PR and open a more manageable one.

In the meantime, we suggest that reviewers only focus on the changes made to the conceptual schema (`docs/M2ConceptualSchema.html`/[`docs/M2ConceptualSchema.png`](https://github.com/DASSL/Gradebook/blob/ab9152f046bbf481bfd8a4221ad4189ebfcbe030/docs/M2ConceptualSchema.png)) and logical schema ([`docs/M2LogicalSchema.docx`](https://github.com/DASSL/Gradebook/blob/1af25da9770efe70f3e92d96f846b0a26d63cf04/docs/M2LogicalSchema.docx)), and verify it against the current Gradebook physical schema ([`dev`:`src/db/createTables.sql`](https://github.com/DASSL/Gradebook/blob/dev/src/db/createTables.sql)).

**Comment by MatthewChastain** [comment]
I think the suggestion to limit the scope of this PR to only the changes required for M2 is a good idea. This will allow for DASSL members to get their reviews in quicker for the components involved in M2.

**Comment by jrm86** [comment]
Thanks for the feedback @MatthewChastain.  This PR will be closed, and the remaining M2 changes will be addressed in an upcoming PR.

**Pull request closed without merging**
