### PR TITLE
Updated OpenClose Import Procedure

### LINKED ISSUE #34: createRosterImport.sql and openCloseImport.sql are inconsistent
openCloseImport.sql creates functions on the gradebook schema, while createRosterImport.sql creates functions on the public schema then uses a `gradebook.` prefix to refer to the tables.  I thought all functions were to be created on the gradebook schema.

If the reason for the prefixes is that the tables could not be recognized any other way (which is the problem I was having for a while), I think it's because a transaction wasn't started prior to the execution of the function, hence the schema can't be set to gradebook.  We need to start a transaction then set the local schema to gradebook before executing the set of functions then commit once the functions are done, which can be done in the batch files. 

However, if there's a different reason, feel free to close this issue as I'm not sure if this is really an issue or not.

### PR DESCRIPTION
**Pull request by srrollo**
This PR provides an updated OpenClose import procedure, modeled after the updated Roster import procedure.  It also adds a few other changes that were necessary to get the procedure to work correctly.  This should also fix #34 and mostly address #37.

#### General
- The OpenClose import scripts have been moved into the `/src/db/importOpenClose` folder
- A README has been added for the OpenClose import procedure, based on the Roster import README.

#### `importOpenCloseCSV.bat`
- Script file names have been updated

#### `prepareOpenCloseImport.sql`
- All OpenClose import SQL code has been consolidated into `prepareOpenCloseImport.sql`
- All necessary objects for import are created in `pg_temp`
- `InstructorUnnest()` has been removed and merged into a CTE (#37).
- The result of `checkTermSequence()` is stored in a variable, and one call is removed
- The date extraction code was slightly modified due to syntax errors.  For now, I tried to keep it as close to the original as possible while still functioning.
- Comments have been added to try and clarify the array function usage
- `ON CONFLICT DO NOTHING` added to the Instructor `INSERT` statement
- The table returned by the `RETURNING` clause of the instructor `INSERT` statement is now `UNION`ed to the current instructor table.  This fixes an issue where sections would not be inserted if they contained an instructor that already existed in the database.
- A second `UNIQUE` constraint has been added to the `Instructor` table. The `UNIQUE(FName, MName, LName)` constraint will never detect two names as the same if MName is NULL. A `UNIQUE(FName, LName) was added to address this.

Overall, `prepareOpenCloseImport.sql` is still pretty cumbersome, but I think it is somewhat more streamlined now.  The user procedure is definitely improved using the model from the Roster import procedure.

I was able to setup a new database and import all the data using the three new procedures, and I can confirm they all work and are much more user friendly now.

### CODE REVIEW

**Comment by afig** [comment]
Apologies for the delay in giving input.

I agree with @smurthys's comment about the script being streamlined. The script is now much better organized and is easier to maintain. The current behavior of quotes seems to be fine. I also agree that the given solution for the unique instructor names issue is acceptable. Again, as mentioned, we should revisit this at some point. Searching for a final solution is sure to bring up some interesting points. 

I was able to test the import procedure with the Spring 2017 test data. As far as major issues, I only noticed one, where the README states that for `importCourseScheduleCSV.bat`, the season argument can be:

>The "order", name, or code of the season in which the schedule depicts, for example, 'Spring'. (See comments associated with the function `Gradebook.getSeason` for details.)

However, giving the "order" of a season results in an error. This seems to be the result of the `pg_temp.importCourseSchedule` only checking for a match on `name` or `code` on lines 115 and 116 of `prepareCouseScheduleImport.sql`. ~~This query should probably be replaced with a call to `Gradebook.getSeasonOrder`.~~ -- On second thought, it seems as through the `seasonOrder` variable can be used here.

Apart from that, there were some small typos and inconsistencies in comments. Many of these have been carried over and existed for a long time, so I gave all comments in `prepareCourseScheduleImport.sql` a look-over, even those that were not touched by this PR:

- L 17: Given that there are other scripts that need to be run prior to running the script, it might be best to simply state that `prepareDB.psql` is required (or that all scripts that are run by `prepareDB.psql` are required).

- L 19: "CSV" is capitalized here, but "csv" is used elsewhere in the script. `importCourseScheduleCSV.bat` uses "CSV", except when using the `COPY` meta-command. Given that "CSV" is used in file names, I think we should go for "CSV" in comments, but "csv" with the `COPY` command (for consistency with other import scripts).

- L 46: There should probably be a period after the closing bracket.

- L 47: Since "`Essentially, each...`" starts a new paragraph, it should have its leading space removed.

- L 77: Should be "semester".

- L 78: The phrase that makes up this line is difficult to understand.

- L 94: Should be "chronologically".

- L 101: Should be "overridden" (in NOTICE).

- L 110-111: Seems like "Select the most extreme start and end dates from TermDates" would be better (and could go on one line).

- L 125-128: Column names here should start with an uppercase letter for consistency.

- L 134: There is an extra space between "into" and "Gradebook.Section".

- L 138: Missing period at the end of the sentence.

- L 152: Not sure what "clearly" represents here.

- L 175: Left-over comment

- L 186: Column names should probably start with a capital letter. "id" is also un-capitalizes in surrounding lines.

-L 196-198: Comment could be on one line (or might be misplaced). Also, should "is" be "its"?

`importCouseScheduleCSV.bat`:

- L 43: "goto" should probably be capitalized to match the other uses.

I will attempt to import all test CSVs, and test the term sequence facility. I will report back if any other issues arise while performing those tests.

***

Here are some other observations on things to address after M1:

- The current behavior for instructor names with > 3 parts is unconventional. (This might also be an issue with the current schema.)

- At some point, it would be good idea to update the README(s) to explain the fields that the staging table expects, which will allow the procedure to be easily adapted to other course schedule systems.

**Comment by srrollo** [comment]
Thanks for taking the time to look at this so thoroughly, there's a lot in `prepareCourseScheduleImport.sql`.
The issue with using season orders is a good catch, I forgot to replaces that old query with the new `seasonOrder` variable in a couple places.

I've addressed all the issues in the comments you found, and replaces some others that were outdated.

I also agree that the current quote behavior in the batch file is OK.  I think the issue with spaces I was having is related to how powershell executes batch files.

**Comment by smurthys** [comment]
Indeed there is a lot going on in `prepareCourseScheduleImport.sql`. Something like that script is hard to develop from scratch, but retrofitting something that already exists is harder. So, kudos @srrollo for your perseverance and @afig for your review effort.

I am just beginning to test the many pending PRs. I tried importing course schedule and ran into trouble when using a CSV filename with embedded space. For example, I ran the following command in a command window:

`
importCourseScheduleCSV.bat "2004 FallOpenClose.csv" 2004 fall postgres gbnew
`

I got the following error:

`
FallOpenClose.csv""=="" was unexpected at this time.
`

I believe the error is on Line 16 of `importCourseScheduleCSV.bat`. 

If this issue is not fixed, the README (even in roster import) needs to clearly say spaces are not permitted in CSV file path. It is a rather artificial limitation, but it may be acceptable for M1.

I will continue to test and report if I find any other issue.

**Comment by srrollo** [comment]
I just pushed a commit that should allow filenames with spaces.  I needed to make two changes for this:
- The existence check for the filename parameter has been changed to `IF "%~1"=="" GOTO usage`.  `%~1` strips quotes from `%1`, and then we put new quotes around `%1`.  This causes the equality check to work, and fixes the `FallOpenClose.csv""=="" was unexpected at this time.` error.
- The `\COPY` meta command has been changed to `"\COPY CourseScheduleStaging FROM '%~1' WITH csv HEADER"`.  This causes psql to correctly parse filenames with spaces, instead of treating the space as a separator between parameters.

These changes should probably also be applied to the roster import batch file.  I can add them to this PR, if that is OK.

**Comment by smurthys** [comment]
Excellent. I just verified that the procedure works even when CSV file path has an embedded space.

Yes, please make the change to the roster-import procedure as well. Thank you.

**Comment by srrollo** [comment]
Sounds good.  I just pushed a commit with the space fix in `importRosterCSV.bat`.

**Pull request merged**
