### PR TITLE
Add server preparation and improve DB preparation

### PR DESCRIPTION
**Pull request by smurthys**
The commits in this PR significantly enhance (I believe) the procedure and scripts to set up the application's data layer.

Here is a summary of the changes:
- Added new script `prepareServer.sql` to create app-specific role `gradebook` and app-specific user `gb_webapp`. This script is modeled after its namesake in ClassDB.
- Added new script `initializeDB.sql` to set permissions for app-specific role and user. This script is modeled after its namesake in ClassDB, but is also quite different in its handling of permissions.
   - Takes away pretty much all privileges from `PUBLIC` and arranges for the app-specific role to be able to pretty much do anything in the database though we don't have ownership
- Removed Gradebook schema creation from `createTables.sql`, because `initializeDB.sql` now does that work
- Added call to `initializeDB.sql` in `prepareDB.psql`
- Revamped README to incorporate the new scripts. This file has changed quite a bit.

Here are some noteworthy things:
- The app-specific role name and user name are not quoted in the script (intentionally), but psql seems to fold case the -U option it receives. So, you must use `gb_webapp` to log in using psql
- Oddly enough even our web client needs to send `gb_webapp` for login to succeed. So, it is probably something I am doing that requires the use of lower case. Unfortunately, I do not have the time to investigate, and it is not really necessary to fix it now. However, **the web client should probably change the default value of DB user field to lower case**.
- The app-specific user is given a default password in the script `prepareServer.sql`. The admin can change it.
- The installation scripts cause various notices to display. However, this is a previously existing issue: no new display of notice is caused by these commits.

### CODE REVIEW

**Comment by smurthys** [comment]
The best way to test these changes is to follow the README in `/src/db` to create and prepare a new database with a name other than `Gradebook`. 

After the DB is prepared, connect to the new DB only as the use `gb_webapp`:
- Import the 2017 Spring Open Close CSV, its rosters, and attendance data
- Humanize student data
- Run the web client with the DB name set to the new database and DB username set to `gb_webapp`

**Comment by afig** [comment]
I have not fully tested the added functionality, but thought I would add the following information for the time being:

In my testing, it seems like `psql` does not fold case names (it always preserves case), regardless of whether the `-U` option is specified or not.

I will update the client later today to use lowercase default values for "DB Username" and "Database", since it seems like a similar issue exists for database names as well.

**Comment by smurthys** [comment]
Thanks for the review. Commit 6c485ac fixes the issue pointed out and also adds a verification section.

In the process, I noticed that function `pg_temp.importAttendance` in the import attendance procedure causes an error if the input section ID is `NULL`. To overcome this limitation, I added the attribute `RETURNS NULL ON NULL INPUT` to that function. Commit a349d36 includes this change.

**Comment by afig** [comment]
Everything looks good

**Comment by smurthys** [comment]
With this PR merged, I think we can say Milestone M1 is met and create a release. Thanks to all contributors.

**Pull request merged**
