### PR TITLE
Client tasks M1 - Part 2

### PR DESCRIPTION
**Pull request by afig**
This PR addresses the remaining M1 tasks in regards to the web client.

Changes:

- DB Info fields are now placed in a collapsible box. Initially, the box is closed, since the default values should suffice in most situations.

- Added options to the attendance table in a collapsible box. Two options are currently available: "Display 'P' attendance code" and "Display compact table". Both options are disabled by default. Changing either option results in the table automatically updating. Currently, at least for M1, `/attendance` is called again whenever one of these options are changed, rather than using the already obtained table.

- Update error messages and display them using [Materialize's modals](http://materializecss.com/modals.html) rather than JavaScript's `alert()`.

- Update About page to one based on latest version of the repository's README.

Non-M1 changes performed:

- Center-align attendance table and fill to container width.

- Add icons to email and password fields.

***

The test instance I have set up has been updated to the latest version of the client and a recent version of the web server ~~(from commit 53eb0e4b408908adecf632bd98e794dccfebd9da)~~. The database that the test instance is using has been setup using the latest version of all three import scripts.

Edit: The web server on the test instance has been updated to the latest version (from commit 41da447fa21bed2e65fa6f3f83ca08b06024a458).

### CODE REVIEW

**Comment by smurthys** [comment]
I love it, especially the surprise Options in the Attendance tab. I also love the table formatting. OK, I love everything about the client.

To test the application end to end, I created a brand new DB and ran every step in the installation and import procedures (imported all sample data and set sample e-mail addresses by name for instructors). I set the DB Info in the  the client to use my local host and default port, but changed the DB name and DB user name to non-default values. I used `murthys@example.edu` to login and verified that all attendance drop downs show correct data.

The entire verification process went smoothly except for two issues:
- Import Attendance failed to import attendance for one section: see Issue #58  
- Import Course Schedule added duplicate instructors, but that turned out to be a non-issue (#59): I had carefully pulled in changes from about 5 branches in the entire process, but missed the second index newly added to `Instructor` table

Although the client is the only visible portion of the application, that the client works flawlessly is a testament to how well **all three layers--client, web, and db--work and work well together**. 🥇 to us all.

I like the content in the About tab and have the following observations:
- Headings seem too big
   - Change `About Gradebook` to h4
   - Change other headings to `h5`: BTW, `Goals` is presently `h4` whereas others headings are `h3`
- It will be nice if the links open in a new tab/window: opening in the same tab causes loss of data on navigating back

**Comment by afig** [comment]
I agree, it was amazing how everything just fell (relatively) into place thanks to all of the work that everyone put in.

The last commit (df177a8) addresses the remarks about headings and links. 

The Goals heading was a different size due to that being the case in the README. However, on the About page, it definitely looks better being the same size as the others.

The changes were not major, but I would appreciate it if at least one other reviewer looks at the result of the changes, just as a sanity check.

**Comment by smurthys** [comment]
> The Goals heading was a different size due to that being the case in the README. However, on the About page, it definitely looks better being the same size as the others.

I see `Goals` has the same size as other sub-headings in README. What am I missing?

**Comment by srrollo** [comment]
The `Goals` heading appears to be the same size to me as well. Either way, I think `h5` on all the sub-headings looks good.

**Comment by afig** [comment]
Hmm. Sorry about that, the difference must have slipped in while I was tinkering with the HTML. I then interpreted it as being a sub-heading of the initial "Gradebook" section.

**Pull request merged**
