### PR TITLE
Add new OpenClose data - May 2019

### PR DESCRIPTION
**Pull request by afig**
This PR adds `.csv` files for the OpenClose data that has been newly available. The last update occurred in May/June of 2017. The following files were added:

- `2017FallOpenClose-Updated.csv`
- `2018FallOpenClose.csv`
- `2018IntersessionOpenClose.csv`
- `2018SpringBreakOpenClose.csv`
- `2018SpringOpenClose.csv`
- `2018SummerOpenClose.csv`
- `2019FallOpenClose.csv`
- `2019IntersessionOpenClose.csv`
- `2019SpringBreakOpenClose.csv`
- `2019SpringOpenClose.csv`
- `2019SummerOpenClose.csv`

A couple of questions came up during the process:

1. Should we add Spring Break classes? I added them for 2018 and 2019, but it seems like we did not add them during our last scraping. These Spring Break terms have occurred yearly since 2005, but usually only have a few sections at most.
2. I added an updated file for Fall 2017. Between when we did our last scrape and now, the listing of sections grew significantly, likely due to sections that are added during the summer. Should we overwrite the original `2017FallOpenClose.csv` file, have a separate updated file like this PR has now, or should we leave the data as is and remove `2017FallOpenClose-Updated.csv` from the PR?

To cleanup the data, I created [this Python script](https://gist.github.com/afig/36cf0a29511c048614daf0e7cce3624d) to remove lines from the CSV that do not correspond to sections. This script would need to be modified for use later due to hardcoded values, but it should still be helpful.

I have not yet verified that these CSVs can be successfully imported into Gradebook. I will do that within the next couple of days.

### CODE REVIEW

**Comment by smurthys** [comment]
Thanks @afig for the additions. I agree the files should be verified as importable before approving this PR for merge. It will be nice if someone other than you also verifies. I will try that later today, and hopefully others are able to as well. In the meantime, I spot checked the Fall 2019 CS portion and find it to be correct.

Yes, we should add Spring Break sessions, but I don't recall if the `Season` table is prepped for it. In general, "more data always beats smarts", in the sense more data can expose new issues and requirements. However, we can add new files incrementally in another PR.

I feel `2017FallOpenClose-Updated.csv` should simply become `2017FallOpenClose.csv`, but I don't recall how the import script handles conflicts. It possibly just overwrites what exists and that is OK (but I have a feeling it may not handle cases where an instructor changes). Regardless, it is always possible the schedule changes and needs to be re-imported. Frankly, we have not really considered that scenario as requirement.

**Comment by smurthys** [comment]
I tried importing to a brand new Gradebook database. Importing 2004 Fall and Spring schedules worked just fine, but **2019 Spring and Summer files failed*. I believe the issue is that the new files have three additional columns `WL Cap`, `WL Act`, and `WL Rem`

**2019 Spring**
```
C:\>importCourseScheduleCSV.bat 2019SpringOpenClose.csv 2019 Spring postgres gb_data
CREATE TABLE
CREATE FUNCTION
CREATE FUNCTION
ERROR:  extra data after last expected column
CONTEXT:  COPY courseschedulestaging, line 2: "Closed,UG,40422,ACC,201,1,3,Financial Accounting,MR,11:30 am-12:45 pm,01/22-05/19,26,26,0,0,0,0,,,,W..."
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

**2019 Summer**
```
C:\>importCourseScheduleCSV.bat 2019SummerOpenClose.csv 2019 Summer postgres gb_data
CREATE TABLE
CREATE FUNCTION
CREATE FUNCTION
ERROR:  extra data after last expected column
CONTEXT:  COPY courseschedulestaging, line 2: "Open,UG,50080,ACC,202,51,3,Managerial Accounting,TWR,05:25 pm-08:00 pm,07/01-08/03,26,6,20,0,0,0,,,,..."
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

**Comment by smurthys** [comment]
BTW, using the current procedure to import one file at a time is impractical to import 65 files. So, I did a little Excel magic and generated a new batch file to call the existing batch file to import each file. Sadly, the new batch file ends after importing the first file in sequence. I am sure I am overlooking something obvious, but need to attend to other things first. I will come back to it later, but would welcome a tip if someone has on what I am doing wrong.

EDIT: I did remove the PAUSE command at end of `importCourseScheduleCSV.bat` to facilitate repeated calling of that file, but that didn't help.

Batch file to call existing batch file (added `.txt` extension to be able to add the file here):
[importAll.bat.txt](https://github.com/DASSL/Gradebook/files/3244217/importAll.bat.txt)

**Comment by smurthys** [comment]
I confirm that importing 2019 Summer schedule works if the three new columns (`WL Cap`, `WL Act`, and `WL Rem`) are removed. I recommend that, for now, we generate the files without the new columns and also open an issue so we can later address it comprehensively.

**Comment by smurthys** [comment]
I just pushed commits that remove the three new columns. I also replaced the original 2017 Fall file with the "updated" file and deleted the "updated" file. I have tested with a couple of the edited files that import works as expected.

**Comment by afig** [comment]
Thanks for testing these files, answering the two questions, reporting problems and providing a fix @smurthys. I should have noticed the extra columns when creating the files.

I have been busy all weekend, so I haven't had a chance to review all of the comments and changes in detail. However, I'll take a closer look tomorrow afternoon. Thanks again.

**Comment by afig** [comment]
Thanks again @smurthys  for your input and a thorough review of the files. Turns out that the `addReferenceData.sql` file is already adding a Spring Break season (named `Spring_Break`), so that is already taken care of. 

I took a look at the batch file and it would also stop on my machine. An internet search revealed that when a batch file calls another batch file, you should use the [`CALL` command](https://ss64.com/nt/call.html) for the original batch file to be able to resume execution once the called batch file finishes execution. I created a new batch file with this CALL command: [importAll.bat.txt](https://github.com/DASSL/Gradebook/files/3250035/importAll.bat.txt). (This new batch file also removes the `2017FallOpenClose-Updated.csv` file and changes the `Winter` and `Spring Break` seasons to `Intersession` and `Spring_Break`, respectively.) It may still be helpful to remove the `PAUSE` from `importCourseScheduleCSV` when running this file to allow the batch file to run without user interaction.

I opened issue #83 to document the issue related to waitlist data.

**Comment by smurthys** [comment]
Thanks @afig for creating the issue and for the tip about `CALL` command. I just imported all 64 files and got no errors. A spot check shows the new data imports fine and thus feel this PR can be approved.

BTW, nothing to do with this PR, the import procedure presently ignores existing sections which is not right, because section info is updated. Creating a new issue for this and discussing there is appropriate.

**Review by smurthys — APPROVED** [review]
I think the changes are OK to merge.

**Comment by afig** [comment]
Thanks @smurthys. I opened Issue #84 regarding the issue of ignoring sections.

**Pull request merged**
